version: '3'
services:
  mongodb:
    image: mongo:4.0.10
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    labels:
      - SERVICE_NAME=mongodb
      - SERVICE_TAGS=mongo,database,json
    command: mongod --smallfiles

  mongoui:
    image: mongoclient/mongoclient:4.0.1
    network_mode: host
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongodb:27017/test
    hostname: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
